apiVersion: v1
kind: ConfigMap
metadata: 
    name: cart
    namespace: roboshop-dev
    labels:
        project: roboshop
        tier: backend
        service: cart
data:
    REDIS_HOST: {{ .Values.configmap.redisHost | quote }}
    CATALOGUE_HOST: {{ .Values.configmap.catalogueHost | quote }}
    CATALOGUE_PORT: {{ .Values.configmap.cataloguePort | quote }}